import { createHash } from "node:crypto";
import { schema } from "@congruo/db";
import { eq } from "drizzle-orm";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ReportSummary } from "../../../components/report-view";
import { loadReport } from "../../../lib/report-data";
import { db } from "../../../lib/server";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Design system audit — Congruo",
  robots: { index: false, follow: false },
};

export default async function SharedReport({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const tokenHash = createHash("sha256").update(token).digest("hex");
  const link = await db().query.shareLinks.findFirst({
    where: eq(schema.shareLinks.tokenHash, tokenHash),
  });
  if (
    !link ||
    link.revokedAt !== null ||
    (link.expiresAt !== null && link.expiresAt < new Date())
  ) {
    notFound();
  }

  const data = await loadReport(link.snapshotId);
  if (!data) notFound();

  return (
    <main className="mx-auto max-w-4xl p-8">
      <div className="mb-6 flex items-baseline justify-between">
        <h1 className="text-2xl font-semibold">Design system audit</h1>
        <span className="text-xs text-neutral-400">
          Read-only report · generated by Congruo
        </span>
      </div>
      <ReportSummary data={data} basePath={null} />
    </main>
  );
}
